# permissions for end users to edit composes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compose-editor-role
rules:
- apiGroups:
  - docker.com
  resources:
  - composes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - docker.com
  resources:
  - composes/status
  verbs:
  - get
