# permissions for end users to view composes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compose-viewer-role
rules:
- apiGroups:
  - docker.com
  resources:
  - composes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - docker.com
  resources:
  - composes/status
  verbs:
  - get
